rm -rf ../logdir/test_input/*
rm -rf ../logdir/test_output/*
rm -rf ../logdir/test_target/*
rm -rf ../logdir/train_input/*
rm -rf ../logdir/train_output/*
rm -rf ../logdir/train_target/*
rm -rf ../logdir/train_target/*
rm -rf ../logdir/train.events
rm -rf ../logdir/val.events
